repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Lint and auto-fix issues (imports, static checks, etc.)
      - id: ruff-check
        args: [--fix]

      # Format code (Black-compatible)
      - id: ruff-format
